/*
 * File: app/view/MyContainer.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyContainer', {
    extend: 'Ext.Container',
    alias: 'widget.mycontainer',

    config: {
        id: 'home',
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                height: '10%',
                title: 'GPlants'
            },
            {
                xtype: 'image',
                height: '35%',
                itemId: 'myimg',
                top: '9%',
                width: '100%',
                src: 'http://www.elandroidelibre.com/wp-content/uploads/2011/10/androidcamera.png'
            },
            {
                xtype: 'image',
                height: '35%',
                itemId: 'myimg1',
                left: '',
                top: '50%',
                width: '100%',
                src: 'http://tecmo.webfactional.com/gplants/dir.png'
            }
        ],
        listeners: [
            {
                fn: 'onMyimgTap',
                event: 'tap',
                delegate: '#myimg'
            },
            {
                fn: 'onMyimg1Tap',
                event: 'tap',
                delegate: '#myimg1'
            }
        ]
    },

    onMyimgTap: function(image, e, eOpts) {
        Ext.getCmp('tabPanel').setActiveItem(Ext.getCmp('camera'));
    },

    onMyimg1Tap: function(image, e, eOpts) {
        Ext.getCmp('tabPanel').setActiveItem(Ext.getCmp('list'));
    }

});