/*
 * File: app/view/MyList.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyList', {
    extend: 'Ext.dataview.List',
    alias: 'widget.mylist',

    config: {
        id: 'list',
        itemTpl: [
            '<div>List Item {string}</div>'
        ],
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'Previous Photos',
                items: [
                    {
                        xtype: 'button',
                        itemId: 'mybutton',
                        text: 'Back'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onMybuttonTap',
                event: 'tap',
                delegate: '#mybutton'
            }
        ]
    },

    onMybuttonTap: function(button, e, eOpts) {
        Ext.getCmp('tabPanel').setActiveItem(Ext.getCmp('home'));
    }

});